config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_config:
    dst: ~/.config/
    src: .config
  d_vim:
    dst: ~/.vim/
    src: .vim
  d_oh-my-zsh:
    dst: ~/.oh-my-zsh/
    src: .oh-my-zsh
  f_vimrc:
    dst: ~/.vimrc
    src: .vimrc
  f_zshrc:
    dst: ~/.zshrc
    src: .zshrc
profiles:
  w0avs:
    dotfiles:
    - d_config
    - d_vim
    - d_oh-my-zsh
    - f_vimrc
    - f_zshrc
